### ISSUE TITLE
Mermaid upgrade

### ISSUE THREAD

**Issue by fabala** [sinedied/hads#29]
Hi Yohan,

Do you think it would be possible to upgrade Mermaid? I have several little bugs in Gantt rendering that may be fixed by the latest version of Mermaid.

**Comment by sinedied** [comment]
The latest mermaid version is `7.1.2`, so it should install with the current version as it is already.
You can try reinstalling hads with `npm rm -g hads && npm i -g hads` to have the latest mermaid version installed.
