### ISSUE TITLE
Cursor in Editor wrong left margin

### ISSUE THREAD

**Issue by setianke** [sinedied/hads#32]
The Cursor in the Editor has a wrong spacing from the left: 

![image](https://user-images.githubusercontent.com/42773428/44726035-131a9580-aad7-11e8-9aee-efc4e069abb3.png)

tested with all major Browser and different Screen Resolutions.

**Comment by sinedied** [comment]
This bug sometimes occurs as you can see here https://github.com/ajaxorg/ace/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cursor, most often it's when using unicode characters 😞 
As this is related to the Ace editor component, I may consider switching to another editor, for example https://github.com/Microsoft/monaco-editor.

PR welcome 😉

**Comment by jamerson** [comment]
A simple workaround to this is to add `font-family: 'Courier';` in `.ace_editor` selector (style.css file). I;m using Courier but any monospace font should do the work.

**Comment by sinedied** [comment]
@jamerson Thanks for the tip, I'll try that 😉

**Comment by jamerson** [comment]
I can open a PR with that if you prefer

**Comment by sinedied** [comment]
That would be nice, thanks!
